//
//  MergeQiime.swift
//  blast-parser
//
//  Created by João Varela on 31/05/2026.
//

import Foundation
import ArgumentParser

struct MergeQiime: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        abstract: "Merges one or more tab-separated Qiime2 ASV read count files with the best hits of a BLAST search.",
        usage: "blast_parser merge-qiime --asvs <asvs> --blasthits <blasthits> --lineage-db <lineage-db>  [--prefixes <prefixes>] [--output <output>] [--hits-per-asv <hits-per-asv>] [--sort <sort>]",
        aliases: ["mrgq"] )
    
    @Option(name: [.short, .customLong("asvs")],
            help: "Path(s) to table file(s) generated by Qiime2 containing ASVs and their respective read counts and taxonomic classification separated by space(s).")
    var asvs:String
    
    @Option(name: [.customShort("l"), .customLong("lineage-db")],
        help: "Path to the imported ranked lineage database in CSV format.")
    var taxonomyDB:String
        
    @Option(name: [.short, .customLong("prefixes")],
            help: "Prefix(es) to add to the Qiime ASV taxonomic assignment header separated by spaces to distinguish between different classifiers or databases (e.g., 'silva pr2 eukaryome'). [OPTIONAL, default = parent directory name of the directory where the asv file is located, i.e., 2 levels up]")
    var prefixes:String?
    
    @Option(name: [.short, .customLong("blasthits")],
            help: "Path to the BLAST output file using a 13 columns format with following order: qsedid pident length evalue bitscore score nident saccver stitle qcovs staxids sscinames sskingdoms.")
    var blasthits:String
    
    @Option(name: [.short, .customLong("output")],
            help: "Name of the output file. [OPTIONAL, default = (BLASTn output filename)_output.tsv]")
    var outputFile:String? = nil
    
    @Option(name: [.customLong("hits-per-asv")],
            help: "Maximum number of sequences per bin. [OPTIONAL, default = 1]")
    var hitsPerAsv:Int?
    
    @Option(name: [.short, .customLong("sort")],
            help: "Sorting order of the output file, which can be either pident, bitscore or evalue. [OPTIONAL, default = bitscore]")
    var sort:String?
    
    mutating func run() throws {
        guard let parser = BlastQiimeOutputParser(path: blasthits,
                                                  asvs: asvs,
                                                  prefixes: prefixes)
        else {
            throw ValidationError("Could not find a valid Qiime 2 file or a BLASTn hits file to be merged.")
        }
        
        if let hitsPerAsv = self.hitsPerAsv {
            parser.hitsPerASV = hitsPerAsv
        }
        
        if let sort = self.sort {
            if let criterion = BlastHit.SortCriterion(rawValue: sort) {
                try parser.parse(lineageDBPath: taxonomyDB, criterion: criterion)
            } else {
                throw ValidationError("Wrong criterion for sorting the output file. Please use either pident, bitscore or evalue.")
            }
        } else {
            try parser.parse(lineageDBPath: taxonomyDB)
        }
        
        // sets default name
        if outputFile == nil{
            let fileName = URL(fileURLWithPath: blasthits).deletingPathExtension().lastPathComponent
            outputFile = "\(fileName)_merged_output.tsv"
        }
    
        try parser.print(outputFile!)
    }
}
